<EkipmanCard>

    orientation: "vertical"

    size_hint_y: None
    height: "155dp"

    padding: "15dp"

    radius: [15]
    elevation: 2

    MDBoxLayout:

        orientation: "vertical"
        spacing: "5dp"

        MDLabel:
            id: lbl_ad
            bold: True
            font_style: "TitleMedium"

        MDLabel:
            id: lbl_id

        MDLabel:
            id: lbl_sorumlu

        MDLabel:
            id: lbl_tarih

        MDLabel:
            id: lbl_durum
            theme_text_color: "Custom"
