<IstatistikCard>

    orientation: "vertical"

    size_hint_y: None
    height: "100dp"

    padding: "12dp"
    spacing: "4dp"

    radius: [15]
    elevation: 1

    MDIcon:
        icon: root.icon
        theme_text_color: "Custom"
        text_color: app.theme_cls.primary_color
        halign: "left"

    MDLabel:
        text: root.value
        bold: True
        font_style: "H6"

    MDLabel:
        text: root.title
        theme_text_color: "Secondary"
        font_style: "Caption"
