<EkipmanCard>

    size_hint_y: None
    height: "155dp"

    padding: "15dp"

    radius: [18]

    ripple_behavior: True

    on_release:
        root.tiklandi()

    MDBoxLayout:

        orientation: "vertical"

        spacing: "8dp"

        MDLabel:

            id: lbl_ad

            text: ""

            bold: True

            font_style: "TitleMedium"

        MDLabel:

            id: lbl_id

            text: ""

        MDLabel:

            id: lbl_sorumlu

            text: ""

        MDLabel:

            id: lbl_tarih

            text: ""

        MDLabel:

            id: lbl_durum

            text: ""

            theme_text_color: "Custom"
