name: Otomatik APK Derleyici

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Repodaki Kodu Cek
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Sistem Bagimliliklarini Yukle
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev \
            git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev cmake ccache

      - name: Buildozer ve Cython Kur
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" buildozer virtualenv

      - name: Buildozer spec Olustur ve Lisanslari Onayla
        run: |
          buildozer init
          sed -i 's/title = My Application/title = Ekipman Periyodik Kontrol Takibi/g' buildozer.spec
          sed -i 's/package.name = myapp/package.name = ekipman_kontrol_takibi/g' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.isg/g' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,requests,certifi/g' buildozer.spec
          
          # Android SDK Lisanslarini Otomatik Onaylama Komutu:
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "\n89339cd345f002328813197f222668609334e330\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea972e2cc723d37e74d614ece" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

      - name: APK Derle
        run: |
          # Lisans reddini engellemek icin yes borusu ekliyoruz:
          yes | buildozer android debug

      - name: APK Dosyasini Paylas
        uses: actions/upload-artifact@v4
        with:
          name: Ekipman_Periyodik_Kontrol_Takibi_APK
          path: bin/*.apk
