name: Otomatik APK Derleyici
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Buildozer Bagimliliklarini Yukle
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake

      - name: Buildozer Kur
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Buildozer Ayar Dosyasi Olustur ve APK Derle
        run: |
          buildozer init
          # Uygulama adını ve paket kimliğini tanımlıyoruz
          sed -i 's/title = My Application/title = Ekipman Periyodik Kontrol Takibi/g' buildozer.spec
          sed -i 's/package.name = myapp/package.name = ekipman_kontrol_takibi/g' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.isg/g' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,requests,certifi/g' buildozer.spec
          # Android APK Derleme Adımı
          buildozer android debug

      - name: APK Dosyasini Cikti Olarak Paylas
        uses: actions/upload-artifact@v3
        with:
          name: Ekipman_Periyodik_Kontrol_Takibi_APK
          path: bin/*.apk
