name: Otomatik APK Derleyici

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Repodaki Kodu Cek
        uses: actions/checkout@v4

      - name: APK Derle
        run: |
          buildozer --warn_on_root=0 android debug

      - name: APK Dosyasini Paylas
        uses: actions/upload-artifact@v4
        with:
          name: Ekipman_Periyodik_Kontrol_Takibi_APK
          path: bin/*.apk
