ename: Otomatik APK Derleyici

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repositoriyi Klonla
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Disk Alanini Temizle
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo apt-get clean

      - name: Sistem Bagimliliklarini Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-venv \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            ccache \
            zip \
            unzip \
            openjdk-17-jdk

      - name: Python Build Araclarini Kur
        run: |
          python3 -m pip install --upgrade pip setuptools wheel --break-system-packages
          python3 -m pip install "cython<3.0.0" buildozer --break-system-packages

      - name: APK Derle (Buildozer)
        run: |
          yes | buildozer -v android debug

      - name: APK Dosyasini Artifact Olarak Yukle
        uses: actions/upload-artifact@v4
        with:
          name: python-app-apk
          path: bin/*.apk
